name: Build CleanMyDeepin

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

env:
  QT_VERSION: 6.8.0
  CMAKE_VERSION: 3.20.0

jobs:
  build-linux:
    name: Build on Linux
    runs-on: ubuntu-25.04
    strategy:
      matrix:
        arch: [x86_64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          ninja-build \
          pkg-config \
          libgl1-mesa-dev \
          libxkbcommon-dev \
          libxcb-xkb-dev \
          libxcb-icccm4-dev \
          libxcb-image0-dev \
          libxcb-keysyms1-dev \
          libxcb-randr0-dev \
          libxcb-render-util0-dev \
          libxcb-shape0-dev \
          libxcb-sync-dev \
          libxcb-xfixes0-dev \
          libxcb-xinerama0-dev \
          libxcb-dri3-dev \
          libxcb-cursor-dev \
          libxcb-dri2-0-dev \
          libxcb-dri3-dev \
          libxcb-present-dev \
          libxcb-composite0-dev \
          libxcb-ewmh-dev \
          libxcb-res0-dev \
          libxcb-util-dev

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: ${{ env.QT_VERSION }}
        host: linux
        target: desktop
        arch: gcc_64
        modules: 'qtdeclarative qttools qtlinguist'
        cache: true

    - name: Configure CMake
      run: |
        cmake -B build \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_INSTALL_PREFIX=/usr \
          -DBUILD_TESTS=OFF \
          -G Ninja

    - name: Build
      run: |
        cmake --build build --config Release --parallel $(nproc)